POST http://localhost:8080
Content-Type: application/json
ce-id: 1234-1234-1234
ce-source: //storage.googleapis.com/projects/_/buckets/my-bucket
ce-type: google.cloud.storage.object.v1.finalized
ce-specversion: 1.0

{
  "bucket": "my-bucket",
  "name": "file.txt",
  "metageneration": "1",
  "timeCreated": "2021-04-23T07:00:00.000Z",
  "updated": "2021-04-23T07:00:00.000Z"
}
