### 1) Basic Pub/Sub Message Test
POST http://localhost:8080
Content-Type: application/json

{
  "specversion": "1.0",
  "id": "1234567890",
  "source": "//pubsub.googleapis.com/projects/test-project/topics/test-topic",
  "type": "google.cloud.pubsub.topic.v1.messagePublished",
  "data": {
    "message": {
      "data": "SGVsbG8sIFB1Yl9TdWI=",
      "messageId": "123456",
      "publishTime": "2025-01-10T15:01:23.045Z",
      "attributes": {
        "key1": "value1",
        "key2": "value2"
      }
    }
  }
}

### 2) Testing an Empty Data Field
POST http://localhost:8080
Content-Type: application/json
ce-id: empty-data-test
ce-source: //pubsub.googleapis.com/projects/YOUR_PROJECT/topics/empty-topic
ce-type: google.cloud.pubsub.topic.v1.messagePublished
ce-specversion: 1.0

{
  "message": {
    "data": "",
    "messageId": "empty-456"
  }
}

### 3) Large Message Example
POST http://localhost:8080
Content-Type: application/json
ce-id: large-message-001
ce-source: //pubsub.googleapis.com/projects/YOUR_PROJECT/topics/large-topic
ce-type: google.cloud.pubsub.topic.v1.messagePublished
ce-specversion: 1.0

{
  "message": {
    "data": "VGhpcyBpcyBhIGxvbmdlciBtZXNzYWdlIHRvIHRlc3QgY2FwYWNpdHkuIEhlbGxvIEdsb2JhbC4=",
    "messageId": "large-789"
  }
}

### 4) Additional CloudEvent Headers
POST http://localhost:8080
Content-Type: application/json
ce-id: 7777-aaaa-bbbb
ce-source: //pubsub.googleapis.com/projects/YOUR_PROJECT/topics/extra-headers
ce-type: google.cloud.pubsub.topic.v1.messagePublished
ce-specversion: 1.0
ce-subject: projects/YOUR_PROJECT/topics/extra-headers-subject
ce-time: 2024-12-23T12:00:00Z
ce-somethingcustom: CustomHeaderValue

{
  "message": {
    "data": "RXh0cmEgQ2xvdWRFdmVudCBIZWFkZXJz",
    "messageId": "custom-1111"
  }
}
